### ISSUE TITLE
Deploy schema from a json file

### ISSUE THREAD

**Issue by piby180** [azaurus1/terraform-provider-pinot#99]
Hi,
Thanks for this providor! Is it possible to deploy schema from json file instead?

**Comment by azaurus1** [comment]
Hi @piby180, You can use [jsondecode](https://developer.hashicorp.com/terraform/language/functions/jsondecode) to read your json file into terraform and then parse it.

There isn't currently an example for this with schemas, but take a look at the examples for tables: https://github.com/azaurus1/terraform-provider-pinot/blob/main/examples/tables/main.tf, where the `realtime_table_example.json` file is decoded and then used to define the table resource.

**Comment by piby180** [comment]
Thanks! I probably then have to create a module with this logic and reuse it.

In the end we have 100s of tables and I want to deploy both table and schema by just providing path to json file.

**Comment by azaurus1** [comment]
Sure no worries, and feel free to reach out with any questions
